"use client";

import { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { finalizeDisposal, getDisposerDashboard } from "@/app/actions/shipments";
import ProofUpload from "@/components/ProofUpload";
import Link from "next/link";
import QrScanner, { DualScanAllocation } from "@/components/QrScanner";
import { parseUnitBarcode, compareQrAndBarcodeDates, formatUnitBarcode } from "@/lib/barcodeHelper";

export default function DisposePage({ params }: { params: { id: string } }) {
  const router = useRouter();
  const [record, setRecord] = useState<any>(null);
  const [photoBeforeUrl, setPhotoBeforeUrl] = useState('');
  const [photoAfterUrl, setPhotoAfterUrl] = useState('');
  const [videoUrl, setVideoUrl] = useState('');
  
  // Official Certificate details (Auto-generated by default)
  const [certMode, setCertMode] = useState<'auto' | 'custom'>('auto');
  const [customCertificateUrl, setCustomCertificateUrl] = useState('');
  const [disposalMethod, setDisposalMethod] = useState('High-Temperature Incineration (1100°C) & Bio-Thermal Neutralization');
  const [officerName, setOfficerName] = useState('');
  const [certificateNotes, setCertificateNotes] = useState('Consignment verified against manufacturer batch manifest. Batch destroyed completely without hazardous residue.');

  const [scannedUnitBarcodes, setScannedUnitBarcodes] = useState<string[]>([]);
  const [barcodeInput, setBarcodeInput] = useState('');
  const [showCameraScanner, setShowCameraScanner] = useState(false);
  const [scanTamperNotice, setScanTamperNotice] = useState<{ isTampered: boolean; text: string } | null>(null);
  const [error, setError] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [done, setDone] = useState(false);

  const autoCertNumber = `CERT-DISP-${params.id.slice(0, 8).toUpperCase()}`;
  const autoCertificateUrl = `/disposals/${params.id}/certificate`;

  useEffect(() => {
    getDisposerDashboard().then(data => {
      if (data) {
        const found = data.disposalRecords.find((d: any) => d.id === params.id);
        if (found) {
          setRecord(found);
          setOfficerName(found.disposerName || '');
          if (found.scannedUnitBarcodes && Array.isArray(found.scannedUnitBarcodes)) {
            setScannedUnitBarcodes(found.scannedUnitBarcodes);
          } else if (found.batch?.unitBarcodes && Array.isArray(found.batch.unitBarcodes)) {
            setScannedUnitBarcodes(found.batch.unitBarcodes);
          } else if (found.batch?.batchNumber) {
            // Generate sample barcodes for the lot quantity
            const qty = Math.min(found.quantity || found.shipment?.quantity || 10, 50);
            const list: string[] = [];
            for (let i = 1; i <= qty; i++) {
              list.push(`BC-${found.batch.batchNumber.replace(/[^A-Z0-9-]/gi, '')}-${String(i).padStart(4, '0')}`);
            }
            setScannedUnitBarcodes(list);
          }
        }
      }
    });
  }, [params.id]);

  const handleFinalize = async () => {
    if (!photoBeforeUrl || !photoAfterUrl || !videoUrl) {
      setError('Please upload all three physical proofs: Photo before, Photo after, and Video (min 30s).');
      return;
    }

    if (certMode === 'custom' && !customCertificateUrl) {
      setError('Please upload your custom certificate file or switch back to the auto-generated official certificate.');
      return;
    }

    setIsSubmitting(true);
    setError('');

    const fd = new FormData();
    fd.set('disposalId', params.id);
    fd.set('photoBeforeUrl', photoBeforeUrl);
    fd.set('photoAfterUrl', photoAfterUrl);
    fd.set('videoUrl', videoUrl);
    fd.set('scannedUnitBarcodes', JSON.stringify(scannedUnitBarcodes));
    
    // Auto-generated certificate route or custom uploaded file
    const activeCertUrl = certMode === 'custom' && customCertificateUrl ? customCertificateUrl : autoCertificateUrl;
    fd.set('certificateUrl', activeCertUrl);
    fd.set('certificateNumber', autoCertNumber);
    fd.set('disposalMethod', disposalMethod);
    fd.set('officerName', officerName || record?.disposerName || 'Authorized Safety Officer');
    fd.set('certificateNotes', certificateNotes);

    const res = await finalizeDisposal(fd);
    setIsSubmitting(false);
    if (res.success) {
      setDone(true);
    } else {
      setError(res.error || 'Failed to finalize disposal.');
    }
  };

  if (done) return (
    <div className="max-w-xl mx-auto text-center py-16">
      <div className="w-16 h-16 bg-emerald-100 rounded-full flex items-center justify-center mx-auto mb-4">
        <svg className="w-8 h-8 text-emerald-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
        </svg>
      </div>
      <h2 className="text-2xl font-bold text-slate-900">Disposal Complete!</h2>
      <p className="text-slate-500 mt-2">
        The batch has been marked as <strong>Fully Disposed</strong>. The official destruction certificate with all verified details has been generated and filed.
      </p>

      <div className="mt-6 flex flex-col sm:flex-row items-center justify-center gap-3">
        <Link
          href={autoCertificateUrl}
          target="_blank"
          className="w-full sm:w-auto px-6 py-3 bg-emerald-600 text-white rounded-xl font-medium hover:bg-emerald-700 shadow-md shadow-emerald-600/20 flex items-center justify-center gap-2"
        >
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
          </svg>
          Print Official Certificate
        </Link>
        <button
          onClick={() => router.push('/disposer')}
          className="w-full sm:w-auto px-6 py-3 bg-slate-100 text-slate-700 rounded-xl font-medium hover:bg-slate-200 transition-colors"
        >
          Back to Dashboard
        </button>
      </div>
    </div>
  );

  if (!record) return (
    <div className="text-center py-20 text-slate-400">Loading disposal record...</div>
  );

  if (record.status === 'completed') return (
    <div className="max-w-xl mx-auto text-center py-16">
      <h2 className="text-2xl font-bold text-slate-900">Already Completed</h2>
      <p className="text-slate-500 mt-2">This disposal has already been finalized and certified.</p>
      <div className="mt-6 flex items-center justify-center gap-3">
        <Link
          href={record.certificateUrl || autoCertificateUrl}
          target="_blank"
          className="px-6 py-3 bg-emerald-600 text-white rounded-xl font-medium hover:bg-emerald-700"
        >
          📄 View Official Certificate
        </Link>
        <button
          onClick={() => router.push('/disposer')}
          className="px-6 py-3 bg-slate-200 text-slate-700 rounded-xl font-medium hover:bg-slate-300"
        >
          Back to Dashboard
        </button>
      </div>
    </div>
  );

  const isFormValid = photoBeforeUrl && photoAfterUrl && videoUrl && (certMode === 'auto' || customCertificateUrl);

  return (
    <div className="max-w-2xl mx-auto">
      <div className="mb-6">
        <div className="flex items-center justify-between">
          <h1 className="text-2xl font-bold text-slate-900">Complete Disposal</h1>
          <span className="text-xs font-mono font-bold bg-orange-100 text-orange-800 px-2.5 py-1 rounded-lg">
            Record #{params.id.slice(0, 8)}
          </span>
        </div>
        <div className="mt-2 p-4 bg-orange-50 border border-orange-200 rounded-xl">
          <div className="flex items-center justify-between">
            <p className="font-bold text-orange-950 text-base">{record.batch?.medicineName}</p>
            <span className="font-mono text-xs font-bold bg-white text-orange-900 px-2.5 py-0.5 rounded border border-orange-200">
              {record.quantity || record.shipment?.quantity || 0} Units
            </span>
          </div>
          <p className="text-sm text-orange-800 mt-0.5">
            Batch: <strong className="font-mono">{record.batch?.batchNumber}</strong> · Manufacturer: {record.batch?.manufacturerName}
          </p>
        </div>
      </div>

      <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-6 space-y-6">
        <div className="p-4 bg-emerald-50 border border-emerald-200 rounded-xl text-sm text-emerald-900 flex items-start gap-3">
          <span className="text-lg">🛡️</span>
          <div>
            <strong>Smart Auto-Certification Active:</strong> Upload the 3 required physical destruction proofs (Before, After, and Video). The <strong>Official Destruction Certificate</strong> is automatically generated with all batch and facility specifications upon submission.
          </div>
        </div>

        {error && <div className="p-4 bg-red-50 border border-red-100 text-red-700 rounded-xl text-sm font-medium">{error}</div>}

        {/* 1. Photo BEFORE */}
        <ProofUpload
          label="1. Photo BEFORE Disposal"
          accept="image/*"
          required
          onUploaded={setPhotoBeforeUrl}
          hint="Clear photo of all medicine packages and cartons before disposal starts."
        />

        {/* 2. Photo AFTER */}
        <ProofUpload
          label="2. Photo AFTER Disposal"
          accept="image/*"
          required
          onUploaded={setPhotoAfterUrl}
          hint="Clear photo showing the medicines after physical destruction / incineration."
        />

        {/* 3. Video */}
        <ProofUpload
          label="3. Video of Disposal Process (Minimum 30 seconds)"
          accept="video/*"
          required
          onUploaded={setVideoUrl}
          hint="Video recording of the physical disposal process in progress (at least 30 seconds)."
        />

        {/* 4. Official Disposal Certificate (Auto-generated with live details) */}
        <div className="border border-slate-200 rounded-2xl p-5 bg-slate-50/70 space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <label className="text-sm font-bold text-slate-900 flex items-center gap-2">
                <span>4. Official Disposal Certificate</span>
                <span className="text-xs bg-emerald-100 text-emerald-800 font-semibold px-2 py-0.5 rounded-full border border-emerald-200">
                  ✓ Auto-Generated with Details
                </span>
              </label>
              <p className="text-xs text-slate-500 mt-0.5">
                Automatically generated and authenticated with all batch, manufacturer, and disposer parameters.
              </p>
            </div>

            <div className="flex items-center gap-1 bg-white p-1 rounded-xl border border-slate-200 text-xs">
              <button
                type="button"
                onClick={() => setCertMode('auto')}
                className={`px-3 py-1.5 rounded-lg font-medium transition-colors ${
                  certMode === 'auto'
                    ? 'bg-emerald-600 text-white shadow-sm'
                    : 'text-slate-600 hover:text-slate-900'
                }`}
              >
                Auto-Generated
              </button>
              <button
                type="button"
                onClick={() => setCertMode('custom')}
                className={`px-3 py-1.5 rounded-lg font-medium transition-colors ${
                  certMode === 'custom'
                    ? 'bg-slate-800 text-white shadow-sm'
                    : 'text-slate-600 hover:text-slate-900'
                }`}
              >
                Upload Scanned File
              </button>
            </div>
          </div>

          {certMode === 'auto' ? (
            /* Auto-generated Certificate Details & Preview Card */
            <div className="bg-white rounded-xl border border-slate-200 p-4 space-y-3.5">
              <div className="flex items-start justify-between">
                <div>
                  <span className="text-[10px] uppercase font-bold text-emerald-800 tracking-wider">
                    Official Document Reference
                  </span>
                  <p className="font-mono text-sm font-black text-slate-900">{autoCertNumber}</p>
                </div>
                <Link
                  href={autoCertificateUrl}
                  target="_blank"
                  className="px-3 py-1.5 bg-emerald-50 hover:bg-emerald-100 text-emerald-800 border border-emerald-200 rounded-lg text-xs font-bold transition-colors flex items-center gap-1.5"
                >
                  <span>Preview / Print ↗</span>
                </Link>
              </div>

              <div className="grid grid-cols-2 gap-3 text-xs border-t border-b border-slate-100 py-3 text-slate-700">
                <div>
                  <span className="text-slate-500 text-[11px] block">Batch Number:</span>
                  <span className="font-mono font-bold text-slate-900">{record.batch?.batchNumber}</span>
                </div>
                <div>
                  <span className="text-slate-500 text-[11px] block">Medicine Name:</span>
                  <span className="font-semibold text-slate-900">{record.batch?.medicineName}</span>
                </div>
                <div>
                  <span className="text-slate-500 text-[11px] block">Quantity Certified Destroyed:</span>
                  <span className="font-mono font-bold text-emerald-700">
                    {record.quantity || record.shipment?.quantity || 0} units
                  </span>
                </div>
                <div>
                  <span className="text-slate-500 text-[11px] block">Disposal Facility:</span>
                  <span className="font-semibold text-slate-900">{record.disposerName}</span>
                </div>
              </div>

              {/* Optional Customization Fields for Certificate */}
              <div className="space-y-3 pt-1">
                <div>
                  <label className="block text-xs font-medium text-slate-700 mb-1">
                    Destruction Protocol / Method:
                  </label>
                  <select
                    value={disposalMethod}
                    onChange={(e) => setDisposalMethod(e.target.value)}
                    className="w-full text-xs px-3 py-2 rounded-lg border border-slate-200 bg-white text-slate-800 outline-none focus:ring-1 focus:ring-emerald-500"
                  >
                    <option value="High-Temperature Incineration (1100°C) & Bio-Thermal Neutralization">
                      High-Temperature Incineration (1100°C) & Bio-Thermal Neutralization (Standard)
                    </option>
                    <option value="Autoclaving, High-Impact Shredding & Chemical Sterilization">
                      Autoclaving, High-Impact Shredding & Chemical Sterilization
                    </option>
                    <option value="Encapsulation & Inertization in Secure Hazardous Landfill">
                      Encapsulation & Inertization in Secure Hazardous Landfill
                    </option>
                  </select>
                </div>

                <div>
                  <label className="block text-xs font-medium text-slate-700 mb-1">
                    Supervising Environmental Safety Officer:
                  </label>
                  <input
                    type="text"
                    value={officerName}
                    onChange={(e) => setOfficerName(e.target.value)}
                    placeholder="Officer name for digital signature..."
                    className="w-full text-xs px-3 py-2 rounded-lg border border-slate-200 bg-white text-slate-800 outline-none focus:ring-1 focus:ring-emerald-500"
                  />
                </div>
              </div>
            </div>
          ) : (
            /* Custom Upload Fallback */
            <div className="space-y-2">
              <ProofUpload
                label="Upload Scanned Paper Disposal Certificate (PDF or Image)"
                accept="image/*,.pdf"
                required
                onUploaded={setCustomCertificateUrl}
                hint="Upload an externally stamped or signed physical document if required by local auditor."
              />
              <button
                type="button"
                onClick={() => setCertMode('auto')}
                className="text-xs text-emerald-700 hover:underline font-medium"
              >
                ← Switch back to Auto-Generated Certificate
              </button>
            </div>
          )}
        </div>

        {/* 5. Engraved Unit Barcode Verification & Destruction Audit */}
        <div className="border border-slate-200 rounded-2xl p-5 bg-slate-50/70 space-y-4">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
            <div>
              <h3 className="text-sm font-bold text-slate-900 flex items-center gap-2">
                <span>5. Engraved Unit Barcode Verification & Destruction Audit</span>
                <span className="text-xs bg-orange-100 text-orange-900 font-bold px-2 py-0.5 rounded-full font-mono">
                  {scannedUnitBarcodes.length} Units Verified
                </span>
              </h3>
              <p className="text-xs text-slate-500 mt-0.5">
                Scan or confirm individual unit barcodes (bottles, strips, or cream tubes) verified before bio-medical neutralization.
              </p>
            </div>

            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={() => setShowCameraScanner(!showCameraScanner)}
                className="text-xs px-3 py-1.5 bg-blue-50 hover:bg-blue-100 text-blue-700 border border-blue-200 rounded-lg font-semibold transition-colors shrink-0 flex items-center gap-1"
              >
                <span>📷</span>
                <span>{showCameraScanner ? 'Hide Camera' : 'Camera Scanner'}</span>
              </button>

              <button
                type="button"
                onClick={() => {
                  if (record?.batch?.batchNumber) {
                    const qty = Math.min(record.quantity || record.shipment?.quantity || 10, 50);
                    const list: string[] = [];
                    for (let i = 1; i <= qty; i++) {
                      list.push(formatUnitBarcode(record.batch.batchNumber, i, record.batch.mfgDate, record.batch.expDate));
                    }
                    setScannedUnitBarcodes(list);
                  }
                }}
                className="text-xs px-3 py-1.5 bg-white hover:bg-slate-100 text-slate-700 border border-slate-200 rounded-lg font-semibold transition-colors shrink-0"
              >
                ✓ Verify All Lot Units
              </button>
            </div>
          </div>

          {/* Camera Scanner Drawer */}
          {showCameraScanner && (
            <div className="p-3 bg-slate-50 rounded-xl border border-slate-200 space-y-2">
              <QrScanner
                label="Scan Engraved Unit Barcode or Batch QR"
                expectedBatchNumber={record?.batch?.batchNumber}
                expectedMfgDate={record?.batch?.mfgDate}
                expectedExpDate={record?.batch?.expDate}
                onScanned={(val) => {
                  const trimmed = val.trim();
                  if (trimmed) {
                    const parsed = parseUnitBarcode(trimmed);
                    if (parsed.isValid && record?.batch) {
                      const check = compareQrAndBarcodeDates(record.batch.mfgDate, record.batch.expDate, parsed.mfgDate, parsed.expDate);
                      if (!check.isMatch) {
                        setScanTamperNotice({ isTampered: true, text: `🚨 FRAUD/TAMPER WARNING: Engraved barcode dates (MFG: ${parsed.mfgDate || 'N/A'}, EXP: ${parsed.expDate || 'N/A'}) DO NOT MATCH batch manifest (MFG: ${record.batch.mfgDate}, EXP: ${record.batch.expDate})!` });
                      } else {
                        setScanTamperNotice({ isTampered: false, text: `🛡️ Anti-Tamper Verified: Engraved barcode dates match batch manifest.` });
                      }
                    }
                    if (!scannedUnitBarcodes.includes(trimmed)) {
                      setScannedUnitBarcodes(prev => [...prev, trimmed]);
                    }
                  }
                }}
                onDualScanned={(alloc) => {
                  const bc = alloc.unitBarcode || alloc.rawCode;
                  if (bc && !scannedUnitBarcodes.includes(bc)) {
                    setScannedUnitBarcodes(prev => [...prev, bc]);
                  }
                  if (alloc.isDateTampered) {
                    setScanTamperNotice({ isTampered: true, text: alloc.tamperNotice || 'Date tampering detected.' });
                  }
                }}
              />
            </div>
          )}

          {/* Tamper Alert Display */}
          {scanTamperNotice && (
            <div className={`p-3 rounded-xl text-xs font-semibold flex items-center justify-between border ${
              scanTamperNotice.isTampered
                ? 'bg-rose-50 border-rose-200 text-rose-800'
                : 'bg-emerald-50 border-emerald-200 text-emerald-800'
            }`}>
              <span>{scanTamperNotice.text}</span>
              <button
                type="button"
                onClick={() => setScanTamperNotice(null)}
                className="text-slate-400 hover:text-slate-600 ml-2"
              >
                ✕
              </button>
            </div>
          )}

          {/* Barcode Input Form */}
          <div className="flex items-center gap-2">
            <input
              type="text"
              value={barcodeInput}
              onChange={(e) => setBarcodeInput(e.target.value)}
              placeholder="Scan unit barcode on bottle/strip (e.g. B1803-M2609E2809-01)..."
              className="flex-1 text-xs px-3 py-2 rounded-xl border border-slate-200 bg-white font-mono text-slate-800 outline-none focus:ring-2 focus:ring-emerald-500"
            />
            <button
              type="button"
              onClick={() => {
                const trimmed = barcodeInput.trim();
                if (trimmed) {
                  const parsed = parseUnitBarcode(trimmed);
                  if (parsed.isValid && record?.batch) {
                    const check = compareQrAndBarcodeDates(record.batch.mfgDate, record.batch.expDate, parsed.mfgDate, parsed.expDate);
                    if (!check.isMatch) {
                      setScanTamperNotice({ isTampered: true, text: `🚨 FRAUD/TAMPER WARNING: Engraved barcode dates (MFG: ${parsed.mfgDate || 'N/A'}, EXP: ${parsed.expDate || 'N/A'}) DO NOT MATCH batch manifest (MFG: ${record.batch.mfgDate}, EXP: ${record.batch.expDate})!` });
                    } else {
                      setScanTamperNotice({ isTampered: false, text: `🛡️ Anti-Tamper Verified: Engraved barcode dates match batch manifest.` });
                    }
                  }
                  if (!scannedUnitBarcodes.includes(trimmed)) {
                    setScannedUnitBarcodes(prev => [...prev, trimmed]);
                  }
                  setBarcodeInput('');
                }
              }}
              className="px-4 py-2 bg-slate-900 hover:bg-slate-800 text-white font-bold text-xs rounded-xl shadow-xs transition-colors"
            >
              + Add
            </button>
          </div>

          {/* Scanned Barcodes Badges */}
          {scannedUnitBarcodes.length > 0 ? (
            <div className="p-3 bg-white rounded-xl border border-slate-200 max-h-36 overflow-y-auto space-y-1.5">
              <div className="text-[11px] font-bold text-slate-500 uppercase tracking-wider">
                Destroyed Unit Serial Numbers ({scannedUnitBarcodes.length}):
              </div>
              <div className="flex flex-wrap gap-1.5">
                {scannedUnitBarcodes.map((bc, idx) => (
                  <span
                    key={idx}
                    className="inline-flex items-center gap-1.5 font-mono text-[10px] px-2 py-0.5 bg-orange-50 text-orange-950 border border-orange-200 rounded-md font-semibold"
                  >
                    <span>🔥</span>
                    <span>{bc}</span>
                    <button
                      type="button"
                      onClick={() => setScannedUnitBarcodes(prev => prev.filter((_, i) => i !== idx))}
                      className="text-orange-400 hover:text-rose-600 ml-0.5"
                    >
                      ✕
                    </button>
                  </span>
                ))}
              </div>
            </div>
          ) : (
            <div className="p-4 bg-white rounded-xl border border-dashed border-slate-200 text-center text-slate-400 text-xs">
              No unit barcodes scanned yet. Enter barcodes or click "Verify All Lot Units".
            </div>
          )}
        </div>

        {/* Submission Action */}
        <div className="pt-2">
          <button
            onClick={handleFinalize}
            disabled={isSubmitting || !isFormValid}
            className="w-full py-4 bg-emerald-600 text-white font-semibold rounded-xl hover:bg-emerald-700 transition-colors shadow-lg shadow-emerald-600/20 disabled:opacity-40 text-base flex items-center justify-center gap-2"
          >
            {isSubmitting ? (
              <span>Submitting Proofs & Generating Certificate...</span>
            ) : (
              <span>✓ Submit Proofs & Generate Official Certificate</span>
            )}
          </button>
          <p className="text-xs text-center text-slate-500 mt-2">
            This action will mark the batch as <strong>Fully Disposed</strong> and publish the authenticated certificate to the Manufacturer and Host regulators.
          </p>
        </div>
      </div>
    </div>
  );
}
